version: '3'
services:
  filebeat:
    build:
      context: "./filebeat/"
    network_mode: "host"
    volumes:
          - "./filebeat/data/:/usr/share/filebeat/data/:rw"
          - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
          - "./filebeat/prospectors.d:/usr/share/filebeat/prospectors.d:ro"
          - "./filebeat/modules.d:/usr/share/filebeat/modules.d:ro"
          - "/data0/web/logs/:/logs/web/:ro"
          - "/data0/web/vhost/:/logs/project/:ro"
          - "/var/log/audit/:/logs/audit/:ro"
  packetbeat:
    build:
      context: "./packetbeat/"
    network_mode: "host"
    cap_add:
          - NET_ADMIN
    volumes:
          - "./packetbeat/data/:/usr/share/packetbeat/data/:rw"
          - "./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml:ro"

