version: '3'
services:
  filebeat:
    build:
      context: "./filebeat/"
    volumes:
          - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
          - "./filebeat/prospectors.d:/usr/share/filebeat/prospectors.d:ro"
          - "./filebeat/modules.d:/usr/share/filebeat/modules.d:ro"
          - "/data0/web/logs/:/logs/web/:ro"
